// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/courier.proto

/*
Package api is a generated protocol buffer package.

It is generated from these files:
	api/courier.proto
	api/documents.proto

It has these top-level messages:
	GetRequest
	GetResponse
	PutRequest
	PutResponse
	Document
	Envelope
	Entry
	EntryMetadata
	SchemaArtifact
	Page
*/
package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PutOperation int32

const (
	// new value was added
	PutOperation_STORED PutOperation = 0
	// value already existed
	PutOperation_LEFT_EXISTING PutOperation = 1
)

var PutOperation_name = map[int32]string{
	0: "STORED",
	1: "LEFT_EXISTING",
}
var PutOperation_value = map[string]int32{
	"STORED":        0,
	"LEFT_EXISTING": 1,
}

func (x PutOperation) String() string {
	return proto.EnumName(PutOperation_name, int32(x))
}
func (PutOperation) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type GetRequest struct {
	// key is the document key
	Key []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (m *GetRequest) Reset()                    { *m = GetRequest{} }
func (m *GetRequest) String() string            { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()               {}
func (*GetRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *GetRequest) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

type GetResponse struct {
	// value is the document value
	Value *Document `protobuf:"bytes,1,opt,name=value" json:"value,omitempty"`
}

func (m *GetResponse) Reset()                    { *m = GetResponse{} }
func (m *GetResponse) String() string            { return proto.CompactTextString(m) }
func (*GetResponse) ProtoMessage()               {}
func (*GetResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *GetResponse) GetValue() *Document {
	if m != nil {
		return m.Value
	}
	return nil
}

type PutRequest struct {
	// key is the document key
	Key []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// value is the document value
	Value *Document `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
}

func (m *PutRequest) Reset()                    { *m = PutRequest{} }
func (m *PutRequest) String() string            { return proto.CompactTextString(m) }
func (*PutRequest) ProtoMessage()               {}
func (*PutRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *PutRequest) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *PutRequest) GetValue() *Document {
	if m != nil {
		return m.Value
	}
	return nil
}

type PutResponse struct {
	Operation PutOperation `protobuf:"varint,1,opt,name=operation,enum=api.PutOperation" json:"operation,omitempty"`
}

func (m *PutResponse) Reset()                    { *m = PutResponse{} }
func (m *PutResponse) String() string            { return proto.CompactTextString(m) }
func (*PutResponse) ProtoMessage()               {}
func (*PutResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *PutResponse) GetOperation() PutOperation {
	if m != nil {
		return m.Operation
	}
	return PutOperation_STORED
}

func init() {
	proto.RegisterType((*GetRequest)(nil), "api.GetRequest")
	proto.RegisterType((*GetResponse)(nil), "api.GetResponse")
	proto.RegisterType((*PutRequest)(nil), "api.PutRequest")
	proto.RegisterType((*PutResponse)(nil), "api.PutResponse")
	proto.RegisterEnum("api.PutOperation", PutOperation_name, PutOperation_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Courier service

type CourierClient interface {
	// Get retrieves a value from the cache or libri network, if it exists.
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
	// put puts a value into the cache and libri network.
	Put(ctx context.Context, in *PutRequest, opts ...grpc.CallOption) (*PutResponse, error)
}

type courierClient struct {
	cc *grpc.ClientConn
}

func NewCourierClient(cc *grpc.ClientConn) CourierClient {
	return &courierClient{cc}
}

func (c *courierClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	out := new(GetResponse)
	err := grpc.Invoke(ctx, "/api.Courier/Get", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *courierClient) Put(ctx context.Context, in *PutRequest, opts ...grpc.CallOption) (*PutResponse, error) {
	out := new(PutResponse)
	err := grpc.Invoke(ctx, "/api.Courier/put", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Courier service

type CourierServer interface {
	// Get retrieves a value from the cache or libri network, if it exists.
	Get(context.Context, *GetRequest) (*GetResponse, error)
	// put puts a value into the cache and libri network.
	Put(context.Context, *PutRequest) (*PutResponse, error)
}

func RegisterCourierServer(s *grpc.Server, srv CourierServer) {
	s.RegisterService(&_Courier_serviceDesc, srv)
}

func _Courier_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CourierServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Courier/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CourierServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Courier_Put_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CourierServer).Put(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Courier/put",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CourierServer).Put(ctx, req.(*PutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Courier_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.Courier",
	HandlerType: (*CourierServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _Courier_Get_Handler,
		},
		{
			MethodName: "put",
			Handler:    _Courier_Put_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/courier.proto",
}

func init() { proto.RegisterFile("api/courier.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 259 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x90, 0xc1, 0x4b, 0xc3, 0x30,
	0x14, 0xc6, 0x5b, 0x8b, 0x13, 0x5f, 0x37, 0x6d, 0xe3, 0x45, 0x76, 0x10, 0x89, 0x17, 0x19, 0xd8,
	0x41, 0xbd, 0x7b, 0xd9, 0x6a, 0x19, 0x88, 0x2b, 0x59, 0x0f, 0xde, 0x24, 0xce, 0x77, 0x08, 0x6a,
	0x13, 0xdb, 0x44, 0xf0, 0xbf, 0x97, 0x26, 0x1d, 0xd9, 0xc5, 0xdd, 0xc2, 0xfb, 0x7e, 0xf9, 0x25,
	0xef, 0x83, 0x94, 0x2b, 0x31, 0xdf, 0x4a, 0xd3, 0x0a, 0x6c, 0x33, 0xd5, 0x4a, 0x2d, 0x49, 0xc4,
	0x95, 0x98, 0x5e, 0xf4, 0xf3, 0x77, 0xb9, 0x35, 0x5f, 0xd8, 0xe8, 0xce, 0x25, 0xf4, 0x0a, 0xa0,
	0x44, 0xcd, 0xf0, 0xdb, 0x60, 0xa7, 0x49, 0x02, 0xd1, 0x07, 0xfe, 0x5e, 0x86, 0xd7, 0xe1, 0xed,
	0x98, 0xf5, 0x47, 0x9a, 0x43, 0x6c, 0xf3, 0x4e, 0xc9, 0xa6, 0x43, 0x72, 0x03, 0xc7, 0x3f, 0xfc,
	0xd3, 0xa0, 0x45, 0xe2, 0x7c, 0x92, 0x71, 0x25, 0xb2, 0xe5, 0xe0, 0x64, 0x2e, 0xa3, 0x0b, 0x80,
	0xca, 0xfc, 0xef, 0xf4, 0x92, 0xa3, 0x03, 0x92, 0x07, 0x88, 0xad, 0x64, 0x78, 0x78, 0x0e, 0xa7,
	0x52, 0x61, 0xcb, 0xb5, 0x90, 0x8d, 0x75, 0x9d, 0xe5, 0xa9, 0xbd, 0x57, 0x19, 0xbd, 0xde, 0x05,
	0xcc, 0x33, 0xb3, 0x3b, 0x18, 0xef, 0x47, 0x04, 0x60, 0xb4, 0xa9, 0xd7, 0xac, 0x58, 0x26, 0x01,
	0x49, 0x61, 0xf2, 0x54, 0x3c, 0xd6, 0xaf, 0xc5, 0xcb, 0x6a, 0x53, 0xaf, 0x9e, 0xcb, 0x24, 0xcc,
	0x39, 0x9c, 0x2c, 0x5c, 0x65, 0x64, 0x06, 0x51, 0x89, 0x9a, 0x9c, 0x5b, 0xbd, 0x2f, 0x67, 0x9a,
	0xf8, 0x81, 0xfb, 0x14, 0x0d, 0x7a, 0xb6, 0x32, 0x3b, 0xd6, 0x2f, 0x3d, 0xb0, 0x7b, 0x0b, 0xd0,
	0xe0, 0x6d, 0x64, 0x1b, 0xbf, 0xff, 0x0b, 0x00, 0x00, 0xff, 0xff, 0xde, 0x38, 0xec, 0x25, 0xa0,
	0x01, 0x00, 0x00,
}
