version: 2
jobs:
  build:
    docker:
      - image: gcr.io/elxir-core-infra/service-base-build:latest
        auth:
          username: _json_key
          password: $GCR_SVC_JSON
    parallelism: 1
    working_directory: /go/src/github.com/elxirhealth/courier
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-vendor-{{ arch }}-{{ checksum "Gopkg.lock" }}-rdb5.8
      - run: make get-deps
      - run:
          name: install RocksDB
          command: |
            # hack to make sure RocksDB runs on CircleCI machines
            if [[ $(md5sum /usr/local/lib/librocksdb.a | awk '{print $1}') != "5b839a7c9a487ae5235ebc810f4f9cef" ]]; then
              ./build/install-rocksdb.sh
            fi
      - run:
          name: install gorocksdb
          command: ./build/install-gorocksdb.sh
      - save_cache:
          key: v1-vendor-{{ arch }}-{{ checksum "Gopkg.lock" }}-rdb5.8
          paths:
            - vendor
            - /usr/local/lib/librocksdb.a
      - run: make build
      - run: make test
      - run: make acceptance
      - run: make lint
